定义宏=1

diff --git a/unittest b/unittest
--- a/unittest
+++ b/unittest
@@ -52,7 +52,7 @@ while [[ $# -gt 0 ]];do
   shift
 done
 
-#echo "$files"
+echo "$files"
 #files="$*" #files="nuid_checker.cpp nuid_inspect.cpp"
 
 # 收集test_开头的函数
@@ -87,11 +87,11 @@ EXE_CPPFlags="$CPPFlags -fpie"
 SO_CPPFlags="$CPPFlags -fPIC -shared"
 
 # shellcheck disable=2068,2086
-g++ $SO_CPPFlags -DUNIT_TEST $CUSTOM_FLAGS $files -I ./scaffold -o lib"${UINT_TEST}".so || die "build so failed"
+g++ $SO_CPPFlags -DUNIT_TEST=1 $CUSTOM_FLAGS $files -I ./scaffold -o lib"${UINT_TEST}".so || die "build so failed"
 
 export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:-}:.
 # shellcheck disable=2068,2086
-g++ $EXE_CPPFlags -DUNIT_TEST $CUSTOM_FLAGS $UNIT_TEST_CPP -L. -l${UINT_TEST} -o "${UINT_TEST_EXE}" || die "build exe failed"
+g++ $EXE_CPPFlags -DUNIT_TEST=1 $CUSTOM_FLAGS $UNIT_TEST_CPP -L. -l${UINT_TEST} -o "${UINT_TEST_EXE}" || die "build exe failed"
 
 ./${UINT_TEST_EXE}
 rm -f ./${UINT_TEST}
